# Generated by Django 4.2.5 on 2023-09-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('show', models.CharField(max_length=100)),
                ('new', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hero')),
            ],
        ),
        migrations.DeleteModel(
            name='Heros',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='comment'),
        ),
        migrations.AlterField(
            model_name='live',
            name='image',
            field=models.ImageField(upload_to='live'),
        ),
        migrations.AlterField(
            model_name='popular',
            name='image',
            field=models.ImageField(upload_to='popular'),
        ),
        migrations.AlterField(
            model_name='recent',
            name='image',
            field=models.ImageField(upload_to='recent'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='image',
            field=models.ImageField(upload_to='tv'),
        ),
    ]
