# Generated by Django 4.2.5 on 2023-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hero_delete_heros_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='review')),
            ],
        ),
    ]
