# Generated by Django 4.2.5 on 2023-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_premier_delete_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='film')),
            ],
        ),
        migrations.DeleteModel(
            name='Live',
        ),
    ]
