# Generated by Django 4.2.5 on 2023-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_film_delete_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='disk')),
            ],
        ),
    ]
