# Generated by Django 3.2.21 on 2023-11-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_disk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
